### PR TITLE
added BackupRetentionPeriod config

### PR DESCRIPTION
**Pull request by ssuman2-infoblox**
V1 Story: [B-98504](https://www10.v1host.com/InfobloxNewV1/story.mvc/Summary?oidToken=Story%3A889790&RoomContext=TeamRoom%3A699936&concept=TeamRoom)

Added BackupRetentionPolicy flag to configure it for prod and non-prod envs

### CODE REVIEW

**Review by bjeevan-ib — CHANGES_REQUESTED** [review]
should we account aurora workflow?

**Review by abalaven — COMMENTED** [review]
What are we specifying in the `backupRetentionPeriod` field?

**Comment by ssuman2-infoblox** [comment]
> should we account aurora workflow?

@bjeevan-ib I've added this config for DBCluster as well. Usually, backup retention period can't be set to 0 for aurora but the value can be managed with DBCluster.

>  What are we specifying in the backupRetentionPeriod field?

@abalaven this field is used to set the number of days for which automated backups are retained. More about this is here: https://doc.crds.dev/github.com/crossplane/provider-aws/rds.aws.crossplane.io/DBInstance/v1alpha1@v0.40.0#spec-forProvider-backupRetentionPeriod

**Review by abalaven — COMMENTED** [review]
IIUC, the default value for `backupRetentionPeriod` is set to 0 in the values file, which I believe will be added to the configMap. Is there any provision to set the value independent of the CM? The CM only holds default values if I'm not wrong.

**Review by drewwells — CHANGES_REQUESTED** [review]
Use a string and pass it through `time.ParseDuration()`. time.Duration is represented as int64 in nanoseconds, so this will be ridiculous to configure if somebody wants 365 days
`backup: 3.1536e16`

**Comment by ssuman2-infoblox** [comment]
> Use a string and pass it through `time.ParseDuration()`. time.Duration is represented as int64 in nanoseconds, so this will be ridiculous to configure if somebody wants 365 days `backup: 3.1536e16`

@drewwells @pjferrell, as per docs it only accepts value from 0-35 (0 means disabled) and it denotes number of days. We can't set it beyond 35.
image

**Comment by ssuman2-infoblox** [comment]
> IIUC, the default value for `backupRetentionPeriod` is set to 0 in the values file, which I believe will be added to the configMap. Is there any provision to set the value independent of the CM? The CM only holds default values if I'm not wrong.

@abalaven I initially tried using arguments to db-controller to pass such values but it required multiple function signature changes. Also we don't want it to be set at dbclaim level but db-controller so CM seemed a good option as it's already configured to take db-controller config as input.

Added something similar here: https://github.com/infobloxopen/db-controller/pull/172

**Review by drewwells — APPROVED** [review]

**Review by bjeevan-ib — APPROVED** [review]

**Pull request merged**
